SRC = $(addsuffix .c, ft_atoi ft_bzero ft_isalnum ft_isalpha ft_isascii ft_isdigit ft_isprint ft_memchr ft_memcmp ft_memcpy ft_memmove ft_memset ft_strchr ft_strdup ft_strlcat ft_strlcpy ft_strlen ft_strncmp ft_strnstr ft_strrchr ft_tolower ft_toupper)

OBJS :=
BONUS_OBJS :=
SUPP_SRC =
SUPP_OBJS =
NAME = 
CC =
CCFLAGS = -Wall -Wextra -Werror
INC_DIR =
CPPFLAGS = 
RM =
ARNAME =
RANNAME = 


